baseurl = "http://zzamboni.org/"
title = "zzamboni.org"
theme = "gohugo-theme-ananke"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = "zzamboni-org"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
publishDir = "docs"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 30
enableRobotsTXT = true
pygmentsCodeFences = true

[permalinks]
  post = "/post/:slug"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "Musings, ramblings and code"
  twitter = "https://twitter.com/zzamboni"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/tram-zurich.jpg"
  copyright_author = "Diego Zamboni"
